/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package db.fastfood;

import javax.swing.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.SwingUtilities;


public class Connessione {
    final String root="root";
    final String password="Mattiaflamigni2002";
    final String dbName="fastfood";

    final String dbUri = "jdbc:mysql://localhost:3306/" + dbName;
    public void doConnessione() {
        try {
            // Thanks to the JDBC DriverManager we can get a connection to the database
            DriverManager.getConnection(dbUri, root, password);
        } catch (final SQLException e) {
            throw new IllegalStateException("Could not establish a connection with db", e);
        }
    }

    public Connection getConnection() {
        try {
            // Thanks to the JDBC DriverManager we can get a connection to the database
            return DriverManager.getConnection(dbUri, root, password);
        } catch (final SQLException e) {
            throw new IllegalStateException("Could not establish a connection with db", e);
        }
    }
}
